### ISSUE TITLE
route parameters contained / cannot be matched

### ISSUE THREAD

**Issue by marswong** [aisk/vox#26]
[routeToRegexp](https://github.com/aisk/vox/blob/5a09164742633f8c3d54bfcf5420af35b900b0dc/route.go#L79) currently use `\w+` to match parameter, but parameter might contain `/`, especially at the senario of object storage service, we need provide a proxy for objects:

```
GET /dir1/dir2/dir3/file => (route) /{namespace}/{file}
```

**Comment by aisk** [comment]
There was a plan to support route parameters with type, see #1 . And after finished this feature, I think we can add a special route parameter type, which allows contain '/'.

For now, we support writing regexp directly actually, and `routeToRegexp` is a helper for translate common usecasees in route, so I think you can write `.+` in you route?

**Comment by marswong** [comment]
> There was a plan to support route parameters with type, see #1 . And after finished this feature, I think we can add a special route parameter type, which allows contain '/'.
> 
> For now, we support writing regexp directly actually, and `routeToRegexp` is a helper for translate common usecasees in route, so I think you can write `.+` in you route?

I still need named parameters in `req.Params`, let's track it in the typed parameters feature :)
